#! /bin/sh

/bin/zsh $HOME/.config/bspwm/start.sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor HDMI-0 -d 1 3 5 7 9
bspc monitor DVI-D-0 -d 2 4 6 8 0

source $HOME/.cache/wal/mycolors.sh
bspc config border_width         5
bspc config window_gap          30
bspc config focused_border_color $color1
bspc config normal_border_color $background

# bspc config split_ratio          0.52
bspc config split_ratio          0.7
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Code desktop='^2'
bspc rule -a firefox desktop='^3'
bspc rule -a Steam desktop='^4' state=floating
bspc rule -a vlc desktop='^5'
bspc rule -a Pavucontrol state=floating
bspc rule -a Org.gnome.Nautilus desktop='^5' state=floating

$HOME/.config/polybar/launch.sh --material
