#! /bin/sh

xrandr --output DVI-D-0 --mode 1920x1080 --pos 1960x0 --rotate normal --output HDMI-0 --primary --mode 1920x1080 --pos 0x0 --rotate normal --output DP-0 --off --output DP-1 --off

pgrep -x sxhkd > /dev/null || sxhkd &
picom --config $HOME/.config/picom/picom.conf &

bspc monitor -d I II III IV V VI VII VIII IX X
bspc monitor HDMI-0 -d  1 2 3 4 5
bspc monitor DVI-D-0 -d 6 7 8 9 10

bspc config border_width        1 
bspc config window_gap	 	0 
bspc config top_padding		0

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focused_border_color  "#1a1a1a"
bspc config normal_border_color  "#1a1a1a"

bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

xsetroot -cursor_name left_ptr

feh --bg-scale ~/.wallpaper/yosemite2.jpg

killall -q polybar 
polybar main &
polybar secondary &
